### ISSUE TITLE
editTopo.py buggy

### ISSUE THREAD

**Issue by aekiss** [COSIMA/topogtools#9]
Some editTopo.py features no longer work.

e.g. zooming with the scroll wheel gives
```
Traceback (most recent call last):
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-24.01/lib/python3.10/site-packages/matplotlib/cbook.py", line 298, in process
    func(*args, **kwargs)
  File "/g/data/v45/aek156/make_topo/topogtools/./editTopo.py", line 440, in zoom
    All.quadMesh, All.cbar = replot(All)
  File "/g/data/v45/aek156/make_topo/topogtools/./editTopo.py", line 241, in replot
    All.cbar.remove()
  File "/g/data/hh5/public/apps/miniconda3/envs/analysis3-24.01/lib/python3.10/site-packages/matplotlib/colorbar.py", line 1042, in remove
    pos = ax.get_position(original=True)
AttributeError: 'NoneType' object has no attribute 'get_position'
```

**Comment by aekiss** [comment]
It used to work fine - I guess there has been some breaking change in matplotlib since I last used it?

**Comment by aekiss** [comment]
I've fixed this - will push update soon.
